# Generated by Django 4.1.4 on 2023-03-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.CharField(default='https://i.imgur.com/SNl3ZA8.jpg', max_length=100),
        ),
    ]
