# Generated by Django 4.1.4 on 2023-03-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_genre_user_gender_user_location_user_favorite_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_genre',
            field=models.ManyToManyField(to='accounts.genre'),
        ),
    ]
