# Generated by Django 4.2.1 on 2023-06-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_favorite_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.CharField(default='https://i.imgur.com/SNl3ZA8.jpg', max_length=400),
        ),
    ]
