# Generated by Django 4.2.1 on 2023-06-02 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyWatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_read_watched', models.IntegerField(default=0, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('category_id', models.IntegerField(default=0, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('img_url', models.CharField(max_length=400, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('num_episode_or_chapter', models.IntegerField(default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'MyWatchlistItem',
            },
        ),
    ]
